# Agradeço a Deus pelo dom do conhecimento
# Use root/mysql as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql

#  adminer:
#    image: adminer
#    restart: always
#    depends_on: 
#      - db
#    ports:
#      - 8080:8080
