# Agradeço a Deus pelo dom do conhecimento
# Use postgres/postgres as user/password credentials
version: '3.1'

services:

  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres

  adminer:
    image: adminer
    restart: always
    depends_on: 
      - db
    ports:
      - 8080:8080